adds logic for gcn.notices. notices, replace healpix_file if present
nasa-gcn/gcn-email pull request #162
Opened 2024-01-29 18:38 UTC by dakota002

2024-01-29 22:47 UTC, lpsinger requested changes
- [ ] Replace _all_ fields larger than a certain size, not just the `healpix_file` field.
- [ ] Fix CI failures.

2024-01-30 13:59 UTC, dakota002 commented
> * [ ]  Replace _all_ fields larger than a certain size, not just the `healpix_file` field.
> * [ ]  Fix CI failures.

For the first point, is there a size you have in mind? Like are we talking a max string length?

2024-01-30 14:13 UTC, lpsinger commented
> For the first point, is there a size you have in mind? Like are we talking a max string length?

Yes.

2024-01-30 14:32 UTC, dakota002 commented
> > For the first point, is there a size you have in mind? Like are we talking a max string length?
> 
> Yes.

Any rough idea what the cutoff should be? 256, 1000, ?

2024-01-30 14:41 UTC, lpsinger commented
> Any rough idea what the cutoff should be? 256, 1000, ?

Let's start with 512 bytes.

2024-01-30 16:40 UTC, lpsinger requested changes
You need to traverse the entire JSON object, not just the top-level dictionary entries.

2024-01-31 14:29 UTC, lpsinger requested changes
There are a lot of unrelated, non-functional, stylistic changes here. It looks like you ran a code formatter on this. Please do that in a separate MR that contains only the reformatting.

2024-01-31 14:31 UTC, dakota002 commented
What are the linting settings for this project? My vscode keeps replacing stuff on save that I don't intend it to

2024-01-31 14:36 UTC, lpsinger commented
> What are the linting settings for this project? My vscode keeps replacing stuff on save that I don't intend it to

We don't have any. Tell you what, I'll make a PR to set up [black](https://black.readthedocs.io/en/stable/).

2024-01-31 15:29 UTC, lpsinger requested changes

2024-01-31 15:29 UTC, lpsinger commented on gcn_email/core.py
> +                replace_long_values(item, max_length)
- Refactor duplicate code
- Deserialization of JSON can never produce bytes

```suggestion
    if isinstance(data, dict):
        iter = data.items()
    elif isinstance(data, list):
        iter = enumerate(data)
    else:
        return
    for key, value in iter:
        if isinstance(value, str) and len(value) > max_length:
            data[key] = REPLACEMENT_TEXT
        else:
            replace_long_values(value, max_length)
```

2024-01-31 15:29 UTC, lpsinger commented on gcn_email/core.py
> +    )
Undo non-functional formatting change.

2024-01-31 15:38 UTC, lpsinger requested changes
Please rebase to pick up black formatting.

2024-01-31 15:51 UTC, dakota002 commented
Some of my changes got removed in the rebase, fixing now

2024-01-31 16:02 UTC, lpsinger approved these changes

2024-01-31 16:03 UTC, merged